ActiveDirectory/Controllers/DomainUserController.cs
using System.Linq;
using System.Web.Mvc;
using ActiveDirectory.Actions;
using ActiveDirectory.Models;
namespace ActiveDirectory.Controllers
{
    [Compress]
    public class DomainUserController : Controller
    {
        private readonly DBContext _db = new DBContext();
        private readonly DomainUser _domainUser = new DomainUser();
        //protected override void OnException(ExceptionContext filterContext)
        //{
        //    filterContext.ExceptionHandled = true;
        //    Logger.AddLog(filterContext.Exception);
        //    filterContext.Result = RedirectToAction("Index", "ErrorHandler");
        //    filterContext.Result = new ViewResult
        //    {
        //        ViewName = "~/Views/ErrorHandler/Index.cshtml"
        //    };
        //}
        public DomainUserController()
        {
            Login.IsUserLogin();
        }
        [Compress]
        public ActionResult Index(int? number)
        {
            if (number != null || number != 0) TempData["number"] = number;
            if (Request.IsAjaxRequest()) return PartialView();
            return View();
        }
        [Compress]
        public ActionResult UserDetails(string id)
        {
            if (Request.IsAjaxRequest())
            {
                var findUser = UserFinder.FindUser(id, true);
                return PartialView(findUser);
            }
            return RedirectToAction("Index");
        }
        [Compress]
        public ActionResult PendingUser()
        {
            Login.IsAdmin(true);
            if (Request.IsAjaxRequest()) return PartialView();
            return View();
        }
        public ActionResult Create(int? id)
        {
            ViewBag.company = _domainUser.GetCompany();
            if (Request.IsAjaxRequest())
            {
                if (Login.IsAdmin())
                {
                    if (id != null)
                        return PartialView(UserFinder.FindUser(id));
                    return PartialView();
                }
            }
            else
            {
                if (Login.IsAdmin())
                {
                    if (id != null)
                        return View(UserFinder.FindUser(id));
                    return View();
                }
            }
            TempData["layout"] = "sss";
            return View();
        }
        [HttpPost]
        public ActionResult CreateUser(UserProperties user)
        {
            if (user.ID == 0)
            {
                if (Login.IsAdmin())
                {
                    _domainUser.CreateIfIsAdmin(user);
                    return Json("Done", JsonRequestBehavior.AllowGet);
                }
                _domainUser.CreateIfIsNotAdmin(user);
                TempData["olusturuldu"] = "asdasdsa";
                ViewBag.company = _domainUser.GetCompany();
                TempData["layout"] = "sss";
                return RedirectToAction("Create");
            }
            _domainUser.ApproveUser(user);
            TempData["done"] = "done";
            return RedirectToAction("DoneResult", new { user.ID});
        }
        public PartialViewResult Islem(int id)
        {
            Login.IsAdmin(true);
            var ss = UserFinder.FindUser(id);
            return PartialView(ss);
        }
        public ActionResult DoneResult(string id)
        {
            var ss = _db.UserInformations.FirstOrDefault(x => x.EmployeNumber == id);
            TempData["11"] = Request.IsAjaxRequest();
            return PartialView(ss);
        }
    }
}

ActiveDirectory/Views/DomainUser/Create.cshtml
@using ActiveDirectory.Actions
@model ActiveDirectory.Models.UserProperties
@{
    if (TempData["layout"] != null)
    {
        Layout = "~/Views/Shared/_UserLayout.cshtml";
    }
}
<div class="card card-custom">
    <div class="card-header text-center">
        <div class="card-title">
            <h3 class="card-label">Kullanıcı Oluştur</h3>
        </div>
    </div>
    <div class="card-body">
        @using (Ajax.BeginForm("CreateUser", "DomainUser", "", new AjaxOptions {HttpMethod = "POST", OnBegin = "showLoading()", OnSuccess = "Done()"}, new {@class = "form fv-plugins-bootstrap fv-plugins-framework", id = "kt_form"}))
        {
            if (Model != null)
            {
                @Html.HiddenFor(model => model.ID)
            }
            <div class="form-group  row">
                <label class="col-form-label text-right col-lg-3 col-sm-12">Yetki Talebi Tipi</label>
                <div class="col-lg-9 col-md-9 col-sm-12">
                    <select name="YetkiTT" id="YetkiTT" class="form-control select form-control-solid form-control-lg">
                        <option value="0">OTOKOÇWEB ve PC hesabı</option>
                        <option value="1">E-Mail Hesabı</option>
                        <option value="2">OBIS</option>
                        <option value="3">Otonet Hesabı</option>
                        <option value="5">Bentaş</option>
                        <option value="6">Dijital Arşiv(Paperwork)</option>
                        <option value="7">E-Fatura</option>
                        <option value="8">E-Mail</option>
                        <option value="9">File-Server</option>
                        <option value="10">OTOKOÇWEB Sayfa İzinleri</option>
                        <option value="11">Telefon Sistemi(Genel Müdürlük)</option>
                        <option value="12">USB Yetki Talebi</option>
                        <option value="13">Volvo/EfesPro</option>
                        <option value="14">VPN Hesabı</option>
                        <option value="15">Yetki İptali</option>
                    </select>
                </div>
            </div>
            <div class="form-group row">
                <label class="col-form-label text-right col-lg-3 col-sm-12">First Name</label>
                <div class="col-lg-9 col-md-9 col-sm-12">
                    @Html.EditorFor(model => model.FirstName, new {htmlAttributes = new {@class = "form-control form-control-solid form-control-lg"}})
                    <span class="form-text text-muted">FirstName</span>
                </div>
            </div>
            <div class="form-group row">
                <label class="col-form-label text-right col-lg-3 col-sm-12">Last Name</label>
                <div class="col-lg-9 col-md-9 col-sm-12">
                    @Html.EditorFor(model => model.LastName, new {htmlAttributes = new {@class = "form-control form-control-solid form-control-lg"}})
                    <span class="form-text text-muted">Last Name</span>
                </div>
            </div>
            <div class="form-group row">
                <label class="col-form-label text-right col-lg-3 col-sm-12">Employee Number</label>
                <div class="col-lg-9 col-md-9 col-sm-12">
                    @Html.EditorFor(model => model.EmployeNumber, new {htmlAttributes = new {@class = "form-control form-control-solid form-control-lg", type = "number"}})
                    <span class="form-text text-muted">Employee Number</span>
                </div>
            </div>
            <div class="form-group row">
                <label class="col-form-label text-right col-lg-3 col-sm-12">Other Phone Number</label>
                <div class="col-lg-9 col-md-9 col-sm-12">
                    @Html.EditorFor(model => model.OtherPhoneNumber, new {htmlAttributes = new {@class = "form-control form-control-solid form-control-lg"}})
                    <span class="form-text text-muted">Other Phone Number</span>
                </div>
            </div>
            <div class="form-group row">
                <label class="col-form-label text-right col-lg-3 col-sm-12">Company</label>
                <div class="col-lg-9 col-md-9 col-sm-12">
                    <select name="Company" id="Company" onchange="GetCity()" class="form-control form-control-solid form-control-lg">
                        @foreach (var item in ViewBag.company)
                        {
                            <option value="@item">@item</option>
                        }
                    </select>
                    <span class="form-text text-muted">Company</span>
                </div>
            </div>
            <div class="form-group row">
                <label class="col-form-label text-right col-lg-3 col-sm-12">City</label>
                <div class="col-lg-9 col-md-9 col-sm-12 ">
                    <div class=" spinner-primary spinner-right" id="CitySpinner">
                        <select name="City" id="City" onchange="GetManager()" class="form-control form-control-solid form-control-lg ">
                        </select>
                    </div>
                    <span class="form-text text-muted">City</span>
                </div>
            </div>
            <div class="form-group row">
                <label class="col-form-label text-right col-lg-3 col-sm-12">Similar User</label>
                <div class="col-lg-9 col-md-9 col-sm-12">
                    <div class=" spinner-primary spinner-right" id="SimilarSpinner">
                        <select class="form-control form-control-solid form-control-lg" id="Group" name="Group">
                        </select>
                    </div>
                    <span class="form-text text-muted">Similar User</span>
                </div>
            </div>
            <div class="form-group row">
                <label class="col-form-label text-right col-lg-3 col-sm-12">Manager</label>
                <div class="col-lg-9 col-md-9 col-sm-12">
                    <div class="spinner-primary spinner-right" id="ManagerSpinner">
                        <select class="form-control  form-control-solid form-control-lg" id="Manager" name="Manager">
                        </select>
                    </div>
                    <span class="form-text text-muted">Manager</span>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-9 ml-lg-auto">
                    @if (Model != null)
                    {
                        <button type="submit" class="btn btn-success font-weight-bold text-uppercase px-9 py-4">Düzenle</button>
                    }
                    else
                    {
                        if (Login.IsAdmin())
                        {
                            <button type="submit" class="btn btn-success font-weight-bold text-uppercase px-9 py-4">Kullanıcıyı Ekle</button>
                        }
                        else
                        {
                            <button type="submit" class="btn btn-success font-weight-bold text-uppercase px-9 py-4">Onaya Gönder</button>
                        }
                    }
                </div>
            </div>
        }
    </div>
</div>
@if (TempData["olusturuldu"] != null)
{
    <script>
        Swal.fire({
            title: "Kullanıcı Onaya Gönderildi",
            icon: "success",
            allowEscapeKey: false,
            allowOutsideClick: false,
            showConfirmButton: false,
            timer: 1000
        });
    </script>
}

<script src="~/Scripts/Addons/DomainUser/Create.js"></script>
<script>
    function Done() {
        var GetId = document.getElementsByName('EmployeNumber')[0].value;
        $.ajax({
            url: '/DomainUser/DoneResult',
            type: "Get",
            data: {
                ID: GetId,
            },
            beforeSend: function() {

                showLoading();
            },
            success: function(result) {
                $("#RenderCrate").html(result);
            },
            complete: function(aa) {
                $("#GlobalModal").modal("show");
                hideSwall();
            },
            error: function(request, error) {
                alert("Request: " + JSON.stringify(request));
            }
        });
    }
</script>

ActiveDirectory/Views/DomainUser/DisableUser.cshtml
@{
    ViewBag.Title = "Kullanıcı Devre Dışı Bırak";
}
<div class="card card-custom">
    <div class="card-header">
        <div class="card-title">
            <span class="card-icon">
                <i class="flaticon2-error text-primary"></i>
            </span>
            <h3 class="card-label">Devre Dışı Bırak</h3>
        </div>
    </div>
    <div class="card-body">
        <table class="table table-hover table-bordered table-responsive table-sm" id="datatable">
            <thead>
            <tr>
                <th></th>
                <th>
                    First Name
                </th>
                <th>
                    Last Name
                </th>
                <th>
                    Logon Name
                </th>
                <th>
                    Job Title
                </th>
                <th>
                    Department
                </th>
                <th>
                    Manager
                </th>
                <th>
                    OU
                </th>
                <th>Last Logon Time</th>
            </tr>
            </thead>
        </table>

    </div>
</div>
<link href="~/assets/plugins/custom/datatables/datatables.bundle.css" rel="stylesheet"/>

@section Scripts{

    <script src="~/assets/plugins/custom/datatables/datatables.bundle.js"></script>
    <script src="~/Scripts/Addons/DomainUser/DisableUser.js"></script>

}

@if (TempData["disable"] != null)
{
    <script>
        Swal.fire({
            icon: 'Success',
            title: 'Kullanıcı Devre Dışı Bırakıldı'
        })
    </script>
}

ActiveDirectory/Views/DomainUser/DoneResult.cshtml
@model ActiveDirectory.Models.UserProperties
@{
    if ((bool) TempData["11"] != true)
    {
        Layout = "~/Views/Shared/_Layout.cshtml";
    }
}
<style>
    table, th, td {
        border: 1px solid black;
        border-collapse: collapse;
    }
</style>
<div class="row">
    <div class="col-8">
        <div class="card card-custom card-border" id="SendMail">
            <div class="card-body p-0">
                <div class="card-header text-center">
                    Merhaba,<br/>
                    *Çağrı sistemi üzerinden açılmasını talep ettiğiniz hesap bilgileri aşağıdaki gibidir.
                    Mail hesaplarının aktivasyon süreci zaman alacaktır, bilgilerinize.
                </div>

                <table class="table table-bordered">
                    <tr>
                        <td colspan="2" class="text-center" style="text-align: center">KULLANICI HESAP BİLGİLERİ </td>
                    </tr>
                    <tr>
                        <td>Kullanıcı Adı Soyadı</td>
                        <td>@Model.FirstName @Model.LastName</td>
                    </tr>
                    <tr>
                        <td>Unvan</td>
                        <td>@Model.JobTitle</td>
                    </tr>
                    <tr>
                        <td>Bilgisayar Açılış Hesabı</td>
                        <td>@Model.LogonName</td>
                    </tr>
                    <tr>
                        <td>OBIS Açılış Hesabı</td>
                        <td>Giriş yetkisi bulunmamaktadır</td>
                    </tr>
                    <tr>
                        <td>OBISRAC Açılış Hesabı</td>
                        <td>Giriş yetkisi bulunmamaktadır</td>
                    </tr>
                    <tr>
                        <td>OTONET Açılış Hesabı</td>
                        <td>Giriş yetkisi bulunmamaktadır</td>
                    </tr>
                    <tr>
                        <td>Eposta Adresi Açılış Hesabı</td>
                        <td></td>
                    </tr>
                    <tr>
                        <td>Eposta Adresi</td>
                        <td></td>
                    </tr>
                    <tr>
                        <td>Şifre</td>
                        <td>TCKNO bilgisi ile https://hesap.otokoc.com.tr üzerinden alınmalıdır</td>
                    </tr>
                </table>
            </div>
        </div>
    </div>
    <div class="col-4">
        <div class="card card-custom">
            <div class="card-body">
                <div class="card-header text-center">
                    Bilgileri Gönder
                </div>
                <div class="form-group">
                    <label>Email Adresi</label>
                    <input type="email" class="form-control" name="Email" placeholder="Email Adresi Giriniz">
                </div>
                <div class="form-group">
                    <button class="btn btn-bg-success" onclick="SendMail()">Gönder</button>
                </div>
            </div>
        </div>
    </div>
</div>
<script src="~/Scripts/Addons/DomainUser/DoneResult.js"></script>

ActiveDirectory/Views/DomainUser/Index.cshtml
@{
    ViewBag.Title = "Tüm Kullanıcılar";
}
<style>
    #dataTable_wrapper { overflow: auto; }
</style>
<div class="card card-custom ">
    <div class="card-header">
        <div class="card-title">
            <span class="card-icon">
                <i class="flaticon2-error text-primary"></i>
            </span>
            <h3 class="card-label">Tüm Kullanıcılar</h3>
        </div>
    </div>
    <div class="card-body">
        <div id="button-cont" class=""></div>
        <table class="table table-hover table-bordered table-sm  table-responsive" id="datatable">
            <thead>
            <tr>
                <th>
                    Name
                </th>

                <th>
                    Logon Name
                </th>
                <th>
                    Title
                </th>
                <th>
                    Department
                </th>
                <th>
                    Manager
                </th>
                <th>
                    OU
                </th>
                <th>Last Logon Time</th>
                <th></th>
            </tr>
            </thead>
        </table>
    </div>
</div>
<link href="~/assets/plugins/custom/datatables/datatables.bundle.css" rel="stylesheet"/>

<script src="~/assets/plugins/custom/datatables/datatables.bundle.js"></script>
<script src="~/Scripts/Addons/DomainUser/Index.js"></script>

@if (TempData["olusturuldu"] != null)
{
    <script>
        Swal.fire({
            icon: 'Success',
            title: 'Kullanıcı Onaya gönderildi'
        })
    </script>
}

ActiveDirectory/Views/DomainUser/Islem.cshtml
@model ActiveDirectory.Models.UserProperties
<div class="modal-header">
    <h5 class="modal-title">Kullanıcı Bilgileri</h5>
</div>
<div class="row justify-content-center py-12 px-12 py-lg-12 px-lg-12">
    <div class="col-xl-12 col-xxl-12">
        <div class="row justify-content-center">
            <div class="col-xl-12">
                <div class="dl-horizontal">
                    <table id="excell" class="">
                        <tr>
                            <td class=" text-dark font-weight-bolder text-hover-primary mb-1 font-size-lg text-dark text-uppercase">Ad</td>
                            <td>@Model.FirstName</td>
                        </tr>
                        <tr>
                            <td class=" text-dark text-uppercase text-dark font-weight-bolder text-hover-primary mb-1 font-size-lg text-dark text-uppercase ">Soyad</td>
                            <td>@Model.LastName</td>
                        </tr>
                        <tr>
                            <td class=" text-dark text-uppercase text-dark font-weight-bolder text-hover-primary mb-1 font-size-lg text-dark text-uppercase ">Tam Ad</td>
                            <td>@Model.DisplayName</td>
                        </tr>
                        <tr>
                            <td class="text-dark text-uppercase text-dark font-weight-bolder text-hover-primary mb-1 font-size-lg text-dark text-uppercase ">Kullanıcı Giriş Adı(Logon Name)</td>
                            <td>@Model.LogonName</td>
                        </tr>
                        <tr>
                            <td class=" text-dark text-uppercase text-dark font-weight-bolder text-hover-primary mb-1 font-size-lg text-dark text-uppercase ">Telefon Numarası</td>
                            <td>@Model.TelephoneNumber</td>
                        </tr>
                        <tr>
                            <td class=" text-dark text-uppercase  text-dark font-weight-bolder text-hover-primary mb-1 font-size-lg text-dark text-uppercase">Ofis</td>
                            <td>@Model.Office</td>
                        </tr>
                        <tr>
                            <td class=" text-dark text-uppercase text-dark font-weight-bolder text-hover-primary mb-1 font-size-lg text-dark text-uppercase ">web Sitesi</td>
                            <td>@Model.WebPage</td>
                            >
                        </tr>
                        <tr>
                            <td class=" text-dark text-uppercase text-dark font-weight-bolder text-hover-primary mb-1 font-size-lg text-dark text-uppercase ">Fax Numarası</td>
                            <td>@Model.FaxNumber</td>
                        </tr>
                        <tr>
                            <td class="text-dark text-uppercase text-dark font-weight-bolder text-hover-primary mb-1 font-size-lg text-dark text-uppercase ">Adres-Sokak</td>
                            <td>@Model.Street</td>
                        </tr>
                        <tr>
                            <td class=" text-dark text-uppercase text-dark font-weight-bolder text-hover-primary mb-1 font-size-lg text-dark text-uppercase ">Şehir</td>
                            <td>@Model.City</td>
                        </tr>
                        <tr>
                            <td class=" text-dark text-uppercase  text-dark font-weight-bolder text-hover-primary mb-1 font-size-lg text-dark text-uppercase">Posta Kodu</td>
                            <td>@Model.ZipCode</td>
                        </tr>
                        <tr>
                            <td class=" text-dark text-uppercase  text-dark font-weight-bolder text-hover-primary mb-1 font-size-lg text-dark text-uppercase">TC No</td>
                            <td id="EmpNubmer">@Model.EmployeNumber</td>
                        </tr>
                        <tr>
                            <td class=" text-dark text-uppercase text-dark font-weight-bolder text-hover-primary mb-1 font-size-lg text-dark text-uppercase ">Diğer Telefon Numarası</td>
                            <td>@Model.OtherPhoneNumber</td>
                        </tr>
                        <tr>
                            <td class=" text-dark text-uppercase  text-dark font-weight-bolder text-hover-primary mb-1 font-size-lg text-dark text-uppercase">İş Alanı</td>
                            <td>@Model.JobTitle</td>
                        </tr>
                        <tr>
                            <td class=" text-dark text-uppercase text-dark font-weight-bolder text-hover-primary mb-1 font-size-lg text-dark text-uppercase ">Departman</td>
                            <td>@Model.Department</td>
                        </tr>
                        <tr>
                            <td class=" text-dark text-uppercase  text-dark font-weight-bolder text-hover-primary mb-1 font-size-lg text-dark text-uppercase">Şirket</td>
                            <td>@Model.Company</td>
                        </tr>
                    </table>
                    <hr/>
                </div>
                <p>
                    <div class="form-horizontal">
                        <div class="form-group">
                            <div id="buttons">
                                <button class="btn btn-primary float-right" id="OnaylaButton" onclick="IslemYapS(@Model.ID, @Model.EmployeNumber)">Onayla</button>
                                <a class="btn btn-bg-warning text-white float-right " id="Duzenles" style="display: none" onclick="Duzenle(@Model.ID)">Düzenle</a>
                            </div>
                            <select class="form-control form-control-solid form-control-lg col-11" onchange="DuzeltButton()" name="durum" id="durum">
                                <option value="1">Onayla</option>
                                <option value="2">Red</option>
                                <option value="3">Hatalı</option>
                            </select>
                        </div>
                    </div>
                </p>
            </div>
        </div>
    </div>
</div>
<script src="~/Scripts/Addons/DomainUser/Islem.js"></script>

ActiveDirectory/Views/DomainUser/PendingUser.cshtml
@{
    ViewBag.Title = "Onay Bekleyen Kullanıcılar";
}
<div class="card card-custom">
    <div class="card-header">
        <div class="card-title">
            <span class="card-icon">
                <i class="flaticon2-error text-primary"></i>
            </span>
            <h3 class="card-label">Onay Bekleyen Kullanıcılar</h3>
        </div>
    </div>
    <div class="card-body">
        <table class="table table-hover  non-hover dataTable no-footer" id="datatable">
            <thead>
            <tr>
                <th>
                    First Name
                </th>
                <th>
                    Last Name
                </th>
                <th>Yetki Talebi Tipi</th>
                <th>
                    Logon Name
                </th>
                <th>Job Title</th>
                <th>
                    Departmant
                </th>
                <th>
                    Manager
                </th>
                <th>Date</th>
                <th>Status</th>
                <th>
                    Action
                </th>
            </tr>
            </thead>
        </table>
    </div>
</div>
<link href="~/assets/plugins/custom/datatables/datatables.bundle.css" rel="stylesheet"/>

@section Scripts{
    <script src="~/assets/plugins/custom/datatables/datatables.bundle.js"></script>
    <script src="~/Scripts/Addons/DomainUser/PendingUser.js"></script>
}